# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bad Futures
email: badfutures@pm.me
description: > # this means to ignore newlines until "baseurl:"
  Bad writings about possible futures
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://badfutures.github.io" # the base hostname & protocol for your site
twitter_username: badfutures
github_username:  badfutures

# Build settings
markdown: kramdown
